# Generated by Django 5.0.3 on 2024-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, max_length=30)),
                ('pin', models.CharField(max_length=30)),
            ],
        ),
    ]
