# Generated by Django 5.0.3 on 2024-04-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('Themes_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=30)),
                ('theme_color', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='Themes',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='couponapp.themes'),
            preserve_default=False,
        ),
    ]
