# Generated by Django 5.0.3 on 2024-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('Shelter_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('website', models.URLField()),
            ],
        ),
    ]
