# Generated by Django 5.0.3 on 2024-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0005_counsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('Recording_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('audioSegment_number', models.IntegerField(default=0)),
                ('videdoSegment_number', models.IntegerField(default=0)),
                ('recording_date', models.DateField()),
                ('audio_duration', models.DateTimeField()),
                ('video_duration', models.DateTimeField()),
                ('audioFile_size', models.FloatField()),
                ('videoFile_size', models.FloatField()),
            ],
        ),
    ]
