# Generated by Django 5.0.3 on 2024-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0006_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_Log',
            fields=[
                ('incidentLog_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField(max_length=30)),
                ('incident_time', models.DateTimeField(max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
